# Generated by Django 2.1 on 2018-09-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.TipoSala'),
        ),
    ]
