# Generated by Django 2.1 on 2018-10-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pedido',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido'),
        ),
        migrations.AddField(
            model_name='mediacliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cliente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='item',
            field=models.ManyToManyField(to='home.Item'),
        ),
        migrations.AddField(
            model_name='evento',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Reserva'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cliente'),
        ),
        migrations.AddField(
            model_name='contato',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cliente'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cliente'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='evento',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='home.Evento'),
        ),
    ]
