# Generated by Django 2.1 on 2018-08-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180817_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicao',
            old_name='Condicao',
            new_name='condicao',
        ),
    ]
