# Generated by Django 2.1 on 2018-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180817_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.IntegerField()),
                ('inscricaoestadual', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('site', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=20)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
