# Generated by Django 2.1 on 2018-08-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Contato'),
        ),
    ]
