# Generated by Django 2.1 on 2018-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cliente_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos'),
        ),
    ]
