# Generated by Django 2.1 on 2018-08-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180828_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposervico', models.CharField(max_length=20)),
            ],
        ),
    ]
