# Generated by Django 2.1 on 2018-08-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=8, null=True)),
                ('dataini', models.DateTimeField()),
                ('dataterm', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Contato')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Sala')),
                ('servicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Servicos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Cliente')),
            ],
        ),
    ]
