# Generated by Django 2.1 on 2018-10-23 17:29

from django.db import migrations, models
import pedido.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cod',
            field=models.CharField(default=pedido.models.codigo, max_length=6, unique=True),
        ),
    ]
