# Generated by Django 2.1 on 2018-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cod',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
